"""The outer AlphaZero loop: self-play, train, evaluate, repeat.

    for each iteration:
        generate self-play games with the current network
        add the positions to the replay buffer
        take gradient steps against a sample of the buffer
        play the result against the previous best and against alpha-beta
        keep the new network only if it beats the incumbent

The gatekeeping step matters. Training can make a network worse, and without a
gate the next iteration's data is generated by that worse network — the loop
degrades instead of improving. Requiring a win rate above a threshold before
promotion makes the process monotone in practice.
"""

import time
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import torch

from connect4 import arena
from connect4.network import Connect4Net, default_device, load, save
from connect4.selfplay import generate_games
from connect4.train import (
    BATCH_SIZE,
    BUFFER_SIZE,
    LEARNING_RATE,
    ReplayBuffer,
    make_optimizer,
    train_epoch,
)

# A challenger must score above this against the incumbent to be promoted. Above
# 0.5 so that noise alone doesn't promote an equal network.
PROMOTION_THRESHOLD = 0.55


@dataclass
class Config:
    iterations: int = 10
    games_per_iteration: int = 24
    simulations: int = 120
    train_steps: int = 100
    batch_size: int = BATCH_SIZE
    # Stop cleanly after this long, whatever `iterations` says. For an unattended
    # run this matters more than the iteration count: it guarantees a finished
    # best.pt and a complete log rather than whatever state a kill leaves behind.
    max_hours: float | None = None
    buffer_size: int = BUFFER_SIZE
    # Step decay. A fixed rate plateaus early over hundreds of iterations, and
    # the optimiser is rebuilt each iteration anyway, so the schedule is just a
    # function of the iteration number.
    learning_rate: float = LEARNING_RATE
    lr_decay_every: int = 40
    lr_decay_gamma: float = 0.5
    lr_min: float = 5e-5
    parallel_games: int = 24
    eval_games: int = 20
    # Arena games run one search at a time, so their evaluations cannot be
    # batched. A smaller budget here keeps evaluation from dominating the loop;
    # it makes both sides slightly weaker but the comparison stays fair.
    eval_simulations: int = 60
    # Both agents are deterministic, so without randomised openings a match
    # replays the same two games and every promotion decision rests on two data
    # points. See arena.play_match.
    opening_plies: int = 4
    benchmark_depth: int = 4
    benchmark_every: int = 1
    checkpoint_dir: Path = Path("checkpoints")
    seed: int = 0


def learning_rate_for(iteration: int, config: "Config") -> float:
    """Step decay, floored at config.lr_min."""
    decays = (iteration - 1) // config.lr_decay_every
    return max(config.lr_min, config.learning_rate * config.lr_decay_gamma**decays)


@dataclass
class IterationReport:
    iteration: int
    samples: int
    buffer: int
    loss_total: float
    loss_policy: float
    loss_value: float
    vs_incumbent: arena.MatchResult | None = None
    promoted: bool = False
    vs_benchmark: arena.MatchResult | None = None
    learning_rate: float = LEARNING_RATE
    elapsed: float = 0.0
    extras: dict = field(default_factory=dict)

    def __str__(self) -> str:
        parts = [
            f"iter {self.iteration:>2}",
            f"samples {self.samples:>5}",
            f"buffer {self.buffer:>6}",
            f"loss {self.loss_total:.4f} (p {self.loss_policy:.4f} v {self.loss_value:.4f})",
            f"lr {self.learning_rate:.1e}",
            f"{self.elapsed / 60:.0f}m",
        ]
        if self.vs_incumbent is not None:
            parts.append(f"vs prev {self.vs_incumbent} {'PROMOTED' if self.promoted else 'kept old'}")
        if self.vs_benchmark is not None:
            parts.append(f"vs ab {self.vs_benchmark}")
        return "  |  ".join(parts)


def run(config: Config | None = None, verbose: bool = True) -> list[IterationReport]:
    """Run the training loop and return one report per iteration."""
    config = config or Config()
    device = default_device()
    rng = np.random.default_rng(config.seed)
    torch.manual_seed(config.seed)

    config.checkpoint_dir.mkdir(parents=True, exist_ok=True)

    best = Connect4Net().to(device).eval()
    save(best, config.checkpoint_dir / "iter000.pt")

    buffer = ReplayBuffer(capacity=config.buffer_size)
    reports: list[IterationReport] = []
    started = time.monotonic()
    deadline = None if config.max_hours is None else started + config.max_hours * 3600
    stop_file = config.checkpoint_dir / "STOP"

    try:
        for iteration in range(1, config.iterations + 1):
            if deadline is not None and time.monotonic() >= deadline:
                if verbose:
                    print(f"time budget reached after {iteration - 1} iterations", flush=True)
                break

            # Creating this file asks the loop to finish the current iteration and
            # exit cleanly, without needing the terminal in focus. Ctrl+C works too
            # and is handled below; both paths still write best.pt.
            if stop_file.exists():
                if verbose:
                    print(f"stop file found after {iteration - 1} iterations", flush=True)
                stop_file.unlink()
                break

            # --- self-play with the current best ---------------------------------
            samples = generate_games(
                best,
                games=config.games_per_iteration,
                simulations=config.simulations,
                parallel=config.parallel_games,
                add_noise=True,
                rng=rng,
            )
            buffer.extend(samples)

            # --- train a challenger, starting from the incumbent's weights -------
            challenger = Connect4Net().to(device)
            challenger.load_state_dict(best.state_dict())
            lr = learning_rate_for(iteration, config)
            optimizer = make_optimizer(challenger, learning_rate=lr)
            loss = train_epoch(
                challenger,
                optimizer,
                buffer,
                device,
                steps=config.train_steps,
                batch_size=config.batch_size,
                rng=rng,
            )

            report = IterationReport(
                iteration=iteration,
                samples=len(samples),
                buffer=len(buffer),
                loss_total=loss.total,
                loss_policy=loss.policy,
                loss_value=loss.value,
                learning_rate=lr,
                elapsed=time.monotonic() - started,
            )

            # --- gate: only promote a challenger that actually beats the best ----
            result = arena.play_match(
                arena.network_agent(challenger, config.eval_simulations),
                arena.network_agent(best, config.eval_simulations),
                games=config.eval_games,
                rng=rng,
                opening_plies=config.opening_plies,
            )
            report.vs_incumbent = result
            report.promoted = result.score > PROMOTION_THRESHOLD

            if report.promoted:
                best = challenger.eval()
                save(best, config.checkpoint_dir / f"iter{iteration:03d}.pt")

            # --- fixed benchmark of known strength -------------------------------
            if iteration % config.benchmark_every == 0:
                report.vs_benchmark = arena.play_match(
                    arena.network_agent(best, config.eval_simulations),
                    arena.alphabeta_agent(config.benchmark_depth),
                    games=config.eval_games,
                    rng=rng,
                    opening_plies=config.opening_plies,
                )

            reports.append(report)
            if verbose:
                print(report, flush=True)

    except KeyboardInterrupt:
        if verbose:
            print("\ninterrupted — saving the best network before exit", flush=True)

    # Always, on every exit path: a run that cannot hand back its best network is
    # a wasted night.
    save(best, config.checkpoint_dir / "best.pt")
    return reports