"""Tests for the training step and replay buffer.

Loss going down is not the interesting claim — a broken loss will also go down.
What's tested here is that each term measures what it says it does: the policy loss
is minimised by the target distribution, the value loss by the target value, and a
step on a fixed batch actually reduces both.
"""

import math

import numpy as np
import pytest
import torch

from connect4.board import COLS, ROWS
from connect4.network import Connect4Net
from connect4.selfplay import Sample
from connect4.train import (
    BATCH_SIZE,
    LossBreakdown,
    ReplayBuffer,
    losses,
    make_optimizer,
    to_tensors,
    train_epoch,
    train_step,
)

CPU = torch.device("cpu")


@pytest.fixture
def net() -> Connect4Net:
    torch.manual_seed(0)
    return Connect4Net().to(CPU)


def fake_samples(n: int, seed: int = 0) -> list[Sample]:
    rng = np.random.default_rng(seed)
    samples = []
    for _ in range(n):
        policy = rng.random(COLS).astype(np.float32)
        samples.append(
            Sample(
                state=(rng.random((2, ROWS, COLS)) < 0.2).astype(np.float32),
                policy=policy / policy.sum(),
                value=float(rng.choice([-1.0, 0.0, 1.0])),
            )
        )
    return samples


# --------------------------------------------------------------------------
# replay buffer
# --------------------------------------------------------------------------

def test_buffer_starts_empty():
    assert len(ReplayBuffer()) == 0


def test_buffer_accumulates_samples():
    buffer = ReplayBuffer(capacity=100)
    buffer.extend(fake_samples(10))
    buffer.extend(fake_samples(5, seed=1))
    assert len(buffer) == 15


def test_buffer_evicts_oldest_beyond_capacity():
    """Old data was generated by a weaker network. An unbounded buffer keeps
    dragging the policy toward obsolete targets."""
    buffer = ReplayBuffer(capacity=10)
    buffer.extend(fake_samples(25))
    assert len(buffer) == 10


def test_buffer_sample_returns_the_requested_count():
    buffer = ReplayBuffer()
    buffer.extend(fake_samples(50))
    assert len(buffer.sample(16, np.random.default_rng(0))) == 16


def test_buffer_sample_caps_at_buffer_size():
    """Early iterations have fewer positions than the batch size."""
    buffer = ReplayBuffer()
    buffer.extend(fake_samples(5))
    assert len(buffer.sample(64, np.random.default_rng(0))) == 5


def test_buffer_sample_on_empty_raises():
    with pytest.raises(ValueError):
        ReplayBuffer().sample(4, np.random.default_rng(0))


# --------------------------------------------------------------------------
# tensor conversion
# --------------------------------------------------------------------------

def test_to_tensors_shapes_and_dtypes():
    states, policies, values = to_tensors(fake_samples(8), CPU)

    assert states.shape == (8, 2, ROWS, COLS)
    assert policies.shape == (8, COLS)
    assert values.shape == (8,)
    assert states.dtype == policies.dtype == values.dtype == torch.float32


def test_value_target_is_one_dimensional():
    """(B,) not (B, 1). A trailing dimension broadcasts against the value head's
    (B,) output into a (B, B) loss matrix, which trains slowly and silently."""
    _, _, values = to_tensors(fake_samples(4), CPU)
    assert values.dim() == 1


# --------------------------------------------------------------------------
# the loss terms
# --------------------------------------------------------------------------

def test_policy_loss_is_minimised_by_the_target_distribution():
    """Logits matching the target give a strictly lower loss than any other."""
    target = torch.tensor([[0.7, 0.2, 0.1, 0.0, 0.0, 0.0, 0.0]])
    matching = torch.log(target.clamp_min(1e-9))
    wrong = torch.log(torch.tensor([[0.0, 0.0, 0.0, 0.0, 0.1, 0.2, 0.7]]).clamp_min(1e-9))
    value = torch.zeros(1)

    good, _ = losses(matching, value, target, value)
    bad, _ = losses(wrong, value, target, value)

    assert good < bad


def test_policy_loss_equals_entropy_when_prediction_matches_target():
    """Cross-entropy against a soft target bottoms out at the target's entropy,
    not at zero. Worth knowing, or a plateauing loss looks like a bug."""
    target = torch.tensor([[0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0]])
    logits = torch.log(target.clamp_min(1e-30))
    zero = torch.zeros(1)

    policy_loss, _ = losses(logits, zero, target, zero)

    assert float(policy_loss) == pytest.approx(math.log(2), abs=1e-4)


def test_value_loss_is_zero_on_an_exact_match():
    target = torch.tensor([1.0, -1.0, 0.0])
    _, value_loss = losses(
        torch.zeros(3, COLS), target, torch.full((3, COLS), 1.0 / COLS), target
    )
    assert float(value_loss) == pytest.approx(0.0)


def test_value_loss_grows_with_error():
    logits = torch.zeros(2, COLS)
    policy = torch.full((2, COLS), 1.0 / COLS)
    target = torch.tensor([1.0, 1.0])

    _, near = losses(logits, torch.tensor([0.9, 0.9]), policy, target)
    _, far = losses(logits, torch.tensor([-0.9, -0.9]), policy, target)

    assert far > near


# --------------------------------------------------------------------------
# training steps
# --------------------------------------------------------------------------

def test_train_step_reduces_loss_on_a_fixed_batch(net):
    """Overfitting one batch is the cheapest end-to-end check that gradients flow
    through both heads."""
    optimizer = make_optimizer(net, learning_rate=1e-2)
    batch = fake_samples(32)

    first = train_step(net, optimizer, batch, CPU)
    for _ in range(30):
        last = train_step(net, optimizer, batch, CPU)

    assert last.total < first.total
    assert last.policy < first.policy
    assert last.value < first.value


def test_train_step_updates_every_parameter(net):
    """A parameter with no gradient means a disconnected branch — e.g. a head
    whose output never reaches the loss."""
    optimizer = make_optimizer(net)
    before = {name: p.clone() for name, p in net.named_parameters()}

    train_step(net, optimizer, fake_samples(16), CPU)

    unchanged = [
        name
        for name, p in net.named_parameters()
        if torch.equal(p, before[name]) and p.requires_grad
    ]
    assert unchanged == []


def test_train_step_returns_a_finite_breakdown(net):
    result = train_step(net, make_optimizer(net), fake_samples(8), CPU)

    assert isinstance(result, LossBreakdown)
    assert math.isfinite(result.total)
    assert result.total == pytest.approx(result.policy + result.value, abs=1e-5)


def test_train_epoch_leaves_the_network_in_eval_mode(net):
    """Search, arena and checkpointing all need eval mode. A network left in
    train() has predictions that depend on batch composition."""
    buffer = ReplayBuffer()
    buffer.extend(fake_samples(64))

    train_epoch(net, make_optimizer(net), buffer, CPU, steps=3, batch_size=16)

    assert net.training is False


def test_train_epoch_returns_the_mean_loss(net):
    buffer = ReplayBuffer()
    buffer.extend(fake_samples(64))

    result = train_epoch(
        net, make_optimizer(net), buffer, CPU, steps=4, batch_size=16,
        rng=np.random.default_rng(0),
    )

    assert math.isfinite(result.total)
    assert result.total > 0
